### PR TITLE
Fix documentation on intel hw accel, in sync with official docs

### PR DESCRIPTION
**Pull request by Oberau**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-jellyfin/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

### CODE REVIEW

**Comment by Oberau** [comment]
i just read you rather have an issue for doc changes, will do that next time.

**Comment by Roxedus** [comment]
This is a good PR, please do the changes in the correct file, as outlined in the contributing file.

**Comment by Oberau** [comment]
I have made the changes to the correct file now. Can you discard changes to wrong file when processing this pull request?

**Comment by Oberau** [comment]
i have tried your image this morning with the mount point as provided in the readme, it did not work. Only after providing the updated mounts as provided in official docs, and it this PR did it work. 

Im streaming right now with this compose config: 
image

**Comment by Oberau** [comment]
okay more testing i find it works with /dev/dri, it turns out my first to get it working i used wrong devices syntax. 
This issue was because no compose example for adding devices is given in your docs.
So there is still a fix needed by showing the right optional parameters in the README for exposing the devices in dockercompose

**Comment by aptalca** [comment]
Feel free to add a blurb for the compose syntax, but we only support mapping `/dev/dri` and not specific devices, because that would break the permission changes we do that's required for a lot of nas users.

And no links to the official docs because they are not applicable here for the above mentioned reason.

**Comment by Oberau** [comment]
isn't the fix to go into readme-vars and put `opt_param_device_map: true` so your pipeline renders these options in the docs?

My github workspaces seems to be having issues with git so unable to changing anything in this PR. Could you do this fix and close this PR?

**Pull request closed without merging**
