### PR TITLE
Update jellyfin-ffmpeg to jellyfin-ffmpeg5

### PR DESCRIPTION
**Pull request by joshuaboniface**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-jellyfin/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
The package name in our repos was updated to ensure backwards
compatibility with ffmpeg4 for 10.7.z and older. Thus, the latest
version for 10.8.0 is actually "jellyfin-ffmpeg5" instead. Update this
in the various dockerfiles and in the package_versions.txt file.

## Benefits of this PR and context:
Ensures that the latest FFMpeg version is available in the LSIO Jellyfin image.

## How Has This Been Tested?
Tested via official Jellyfin channels as working (e.g. `apt install`, functionality of FFMpeg 5.x, etc.)

## Source / References:
N/A

### CODE REVIEW

**Comment by nyanmisaka** [comment]
https://github.com/linuxserver/docker-jellyfin/pull/155 can be cherry picked to the master branch now.

**Comment by aptalca** [comment]
Just to clarify, are the Intel drivers no longer needed for opencl? Did the Ubuntu repo version of mesa cover all that's needed?

**Comment by nyanmisaka** [comment]
> Just to clarify, are the Intel drivers no longer needed for opencl? Did the Ubuntu repo version of mesa cover all that's needed?

Intel media drivers are included in jellyfin-ffmpeg5. OpenCL still requires the mod.
Mesa is only used on AMD.

**Review by aptalca — APPROVED** [review]

**Comment by aptalca** [comment]
@nyanmisaka with regards to the opencl mod, should we switch that to trigger on the latest github releases, where it would always install the latest, pin it to a specific version, and/or should we use the intel apt repo to install?

For plex, we use the intel apt repo but we [pin it to a specific version](https://github.com/linuxserver/docker-plex/blob/master/Dockerfile#L32) (what they test with) and newer versions don't work. Emby includes static libs in their package so we don't install any opencl packages for them.

Alternatively, we can add the opencl packages to the main image and deprecate the mod (looks like tone mapping is pretty stable now for jellyfin).

Thanks

**Comment by nyanmisaka** [comment]
@aptalca 
It’s hard to say since we all don’t know when Intel OpenCL runtime (gmmlib lib specifically) will make breaking changes again in their API. 

Plex has been suffering from this for a long time so they decided to pin to 21.49. We adapted the new API in our ffmpeg so we don’t need a pinned OpenCL runtime.

But I think it’s safe to pin the latest release of OpenCL runtime in the main images for the time being. And we should do some test to ensure it works before bumping the versions.

Intel’s apt repo is not being actively maintained compared with their compute-runtime github releases, which is not good for us when breaking changes hit us.

**Pull request merged**
