### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by astronaute-nope**
According to https://jellyfin.org/docs/general/administration/hardware-acceleration/#hardware-acceleration-on-raspberry-pi-3-and-4 OpenMAX is deprecated.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-jellyfin/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

### CODE REVIEW

**Comment by j0nnymoe** [comment]
You've not read the contributing guidelines correctly, they specifically say not to edit the readme file.

**Comment by astronaute-nope** [comment]
Oh ! Sorry so I need to edit readme-vars.yml right ?

**Comment by aptalca** [comment]
You checked the box, but did you _really_ read the contributing guideline?

**Comment by astronaute-nope** [comment]
Fair enough. Will do as written : 
If this is a fix for a typo (in code, documentation, or the README) please file an issue and let us sort it out. We do not need a PR 

So I'll open an issue

**Pull request closed without merging**
