### PR TITLE
Add Jellyfin binary environmentals

### PR DESCRIPTION
**Pull request by Artiume**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-jellyfin/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Source / References:

https://github.com/jellyfin/jellyfin/issues/4779
https://github.com/linuxserver/docker-jellyfin/issues/22
https://github.com/linuxserver/docker-jellyfin/issues/48
https://github.com/linuxserver/docker-jellyfin/issues/65

### CODE REVIEW

**Review by aptalca — APPROVED** [review]

**Comment by Artiume** [comment]
@aptalca sorry to make you review it again, but i wanted to add the other environmentals for migration so a few more tickets can be closed out.

**Comment by aptalca** [comment]
No worries, PRs are always welcome.

Except, I'm not too fond of listing all those new vars that are meaningless to 99% of the users. I like to keep the env var list as concise as possible, so as not to confuse new users.

The ip advertise var is fine and is useful. But the others can perhaps be moved to a blurb on the application setup section. And also, isn't only one of those necessary for migration anyway (cache one maybe)? I thought the others were pretty much the same?

**Comment by Artiume** [comment]
yeah, that makes sense. let me redo it.

**Comment by Artiume** [comment]
Should be good now

**Comment by Artiume** [comment]
this is ready to merge

**Review by aptalca — APPROVED** [review]

**Pull request merged**
