### PR TITLE
Hint the OpenCL mod for tone-mapping on QSV

### PR DESCRIPTION
**Pull request by nyanmisaka**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-jellyfin/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
- Hint the OpenCL mod for tone-mapping on QSV

## Benefits of this PR and context:
- Many Intel users haven't heard of the OpenCL mod so that I have to tell them all the time.

## Source / References:
https://github.com/linuxserver/docker-mods/tree/jellyfin-opencl-intel

### CODE REVIEW

**Comment by Roxedus** [comment]
This change will not stick

**Comment by nyanmisaka** [comment]
> This change will not stick

Any better idea or example to do this?

Or I just link to the https://mods.linuxserver.io/?mod=jellyfin

**Comment by Roxedus** [comment]
Reread the contributing guideline

**Comment by nyanmisaka** [comment]
> Reread the contributing guideline

Sorry for that. I correct the target file to `readme-vars.yml` now.

**Review by aptalca — APPROVED** [review]

**Pull request merged**
